### ISSUE TITLE
Generated voronoi regions interesect with geometries

### ISSUE THREAD

**Issue by christianayala10** [longavailable/voronoi-diagram-for-polygons#4]
I have generated the voronoi regions (in red) for the geometries in blue. As it can be seen, the resulting voronoi regions interset with the original geometries. Any idea?

![image](https://user-images.githubusercontent.com/25979779/191066393-cea31b1c-58f3-4e98-883f-d8fc33b03a1b.png)

**Comment by longavailable** [comment]
[Voronoi diagram for polygons](https://github.com/longavailable/voronoi-diagram-for-polygons) is based on [shapely.ops.voronoi_diagram](shapely.ops.voronoi_diagram). 

As it mentioned,

> All vertices of the geometry will be used as the input points to the diagram.

Let us have a look on the geometries from your inputs.

**Too less** vertices!

Then it should be added more vertices along their edges.

I added a few to functions to reach it. See [v0.1.3](https://github.com/longavailable/voronoi-diagram-for-polygons/commit/895cf907d6bcc9aeba0b5079c4746f53b584ef62).

When you type: 

`vd = voronoiDiagram4plg(builtup, boundary)`

It return the same output as usual.

When:

`vd = voronoiDiagram4plg(input, boundary, densify=True)`

It will proceed a automatical densifying preprocessing. And it will return the following.

![image](https://user-images.githubusercontent.com/24582280/202351150-022ed11b-e88d-4adf-9373-81b0393c80e7.png)

It looks better!

You can also assign an expected spacing to `spacing` parameter, for example:

`vd = voronoiDiagram4plg(input, boundary, densify=True, spacing=5000)`

At last, when you post a specific issue, it 's better to upload the related attachments. That will be time-saving for a reviewer.
