### ISSUE TITLE
Unclear data format - missing input files

### ISSUE THREAD

**Issue by leshaved** [longavailable/voronoi-diagram-for-polygons#5]
Hello, it's unclear in which format the input data for files input.geojson, boundary.geojson should be. Could you please upload them to the repo? Thanks!

**Comment by longavailable** [comment]
Hi @leshaved , this package is totally based on [GeoPandas](https://geopandas.org). In other words, any format that can be converted to [geopandas.GeoDataFrame](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.html#geopandas.GeoDataFrame) object is supported. 

As the [official documentation](https://geopandas.org/en/stable/docs/user_guide/io.html#reading-spatial-data) said:

> geopandas can read almost any vector-based spatial data format including ESRI shapefile, GeoJSON files and more using the command: `geopandas.read_file()`

Hope this help you.
