### ISSUE TITLE
TypeError: 'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by duartejr** [longavailable/voronoi-diagram-for-polygons#6]
Hi. I encountered a problem with some shapefiles being utilized as masks while using Shapely version 2.0.1. The following notice appears during processing: TypeError: The object "MultiPolygon" is not iterable. This error is generated on line 142 in the  "dropHolesBase" function.
This is the line of code with problem:
`return MultiPolygon(Polygon(p.exterior) for p in plg)`

This mistake is brought on by the creation of some Multipolygons that are not interable in Shapely version 2.0.1.
I changed the line to fix the issue.
The new command is: 
`return MultiPolygon(Polygon(p.exterior) for p in list(plg.geoms)`

My issue was resolved, and I hope this can assist others.

**Comment by longavailable** [comment]
Thank @duartejr for your feedback and suggestion.

Exactly. `MultiPolygon` is not iterable any more from [Shapely] 2.0. It was mentioned in [Shapely]'s [user guide](https://shapely.readthedocs.io/en/stable/release/2.x.html#shapely-2-0-api-changes-deprecated-in-1-8).

> Multi-part geometries such as MultiPolygon no longer behave as “sequences”. This means that they no longer have a length, are not iterable, and are not indexable anymore. Use the `.geoms` attribute instead to access individual parts of a multi-part geometry.


[Shapely]: https://github.com/shapely/shapely
