### ISSUE TITLE
Multiple neighbor geometries

### ISSUE THREAD

**Issue by GeorgeKontsevik** [longavailable/voronoi-diagram-for-polygons#8]
if we have too close geometries they do not properly avoid each other's boarders so it is not possible to create those polygons from buildings' polygons
![image](https://user-images.githubusercontent.com/98597244/233947692-dc00ac29-0e67-49b2-b260-fdfbbb0938ad.png)

Also, if geometries are connected to each other this method considers them as different geometries. Probably unary_union could help here. However maybe it is on my side though
![image](https://user-images.githubusercontent.com/98597244/233948525-15c9301d-25dd-4244-af0c-44a968095c93.png)

**Comment by longavailable** [comment]
Please check https://github.com/longavailable/voronoi-diagram-for-polygons/issues/4#issuecomment-1318031958. 

I suppose it may help.

**Comment by longavailable** [comment]
For part 2:

> Also, if geometries are connected to each other this method considers them as different geometries. Probably unary_union could help here. However maybe it is on my side though

I will say yes. A preprocessing for the input is recommended.

**Comment by GeorgeKontsevik** [comment]
Got it thanks, managed to do this on my own.
