### ISSUE TITLE
Duplicated voronoi polygons

### ISSUE THREAD

**Issue by GeorgeKontsevik** [longavailable/voronoi-diagram-for-polygons#9]
Unfortunately the methods results in overlaying voronoi polygons, which just duplicates each other
![image](https://user-images.githubusercontent.com/98597244/233947427-136df666-5049-4bfb-a751-a6dbdb27734d.png)

**Comment by longavailable** [comment]
I can't recognize the input geometries. Check https://github.com/longavailable/voronoi-diagram-for-polygons/issues/4#issuecomment-1318031958 to see if it helps.

**Comment by GeorgeKontsevik** [comment]
Got it, thanks
